name: Update File

on:
  schedule:
    - cron: "0,30 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          bit_api_key: ${{ secrets.API_KEY }}
          csv_location: ${{ env.csv_location }}
        run: python runner.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Add data automatically"
